table Magasins
	lineageTag: 90c6d692-f81b-4a16-912a-60e05c4e1759

	column 'ID magasin'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8d5516cf-49cd-4eee-b80d-d73de4884f82
		summarizeBy: none
		sourceColumn: ID magasin

		annotation SummarizationSetBy = User

	column Magasin
		dataType: string
		lineageTag: 97096a2d-a9fe-44ee-b9d3-be2df06f575e
		summarizeBy: none
		sourceColumn: Magasin

		annotation SummarizationSetBy = User

	column Ville
		dataType: string
		lineageTag: 7c5fd946-be97-49fd-8f61-102684de50e5
		summarizeBy: none
		sourceColumn: Ville

		annotation SummarizationSetBy = User

	column 'Type d''emplacement'
		dataType: string
		lineageTag: 697fef41-2174-4566-9207-a71655d06747
		summarizeBy: none
		sourceColumn: Type d'emplacement

		annotation SummarizationSetBy = User

	column 'Date d''ouverture'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 7dc195fa-3e4e-4a66-8889-4fee74374f5f
		summarizeBy: none
		sourceColumn: Date d'ouverture

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

	partition Magasins = m
		mode: import
		source =
				// Requête : Magasins (dimension)
				// Grain : une ligne = un magasin (50 magasins)
				let
				    // Lecture depuis GitHub (par défaut, fonctionne sur tout poste) ou depuis un dossier local
				    Contenu =
				        if Text.StartsWith(DossierDonnees, "http")
				        then Web.Contents(DossierDonnees & "stores.csv")
				        else File.Contents(DossierDonnees & "stores.csv"),
				    Source = Csv.Document(
				        Contenu,
				        [Delimiter = ",", Columns = 5, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				    ),
				    EntetesPromues = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    TypesAppliques = Table.TransformColumnTypes(
				        EntetesPromues,
				        {
				            {"Store_ID", Int64.Type},
				            {"Store_Name", type text},
				            {"Store_City", type text},
				            {"Store_Location", type text},
				            {"Store_Open_Date", type date}
				        },
				        "en-US"
				    ),
				    // Correction d'une faute de frappe dans la source ("Cuidad" au lieu de "Ciudad").
				    // Sans cette correction, la ville serait mal nommée dans tous les visuels.
				    VilleCorrigee = Table.ReplaceValue(
				        TypesAppliques, "Cuidad de Mexico", "Ciudad de Mexico", Replacer.ReplaceValue, {"Store_City"}
				    ),
				    EmplacementsTraduits = Table.TransformColumns(
				        VilleCorrigee,
				        {
				            {
				                "Store_Location",
				                each Record.FieldOrDefault(
				                    [
				                        Downtown = "Centre-ville",
				                        Commercial = "Zone commerciale",
				                        Residential = "Quartier résidentiel",
				                        Airport = "Aéroport"
				                    ],
				                    _,
				                    _
				                ),
				                type text
				            }
				        }
				    ),
				    ColonnesRenommees = Table.RenameColumns(
				        EmplacementsTraduits,
				        {
				            {"Store_ID", "ID magasin"},
				            {"Store_Name", "Magasin"},
				            {"Store_City", "Ville"},
				            {"Store_Location", "Type d'emplacement"},
				            {"Store_Open_Date", "Date d'ouverture"}
				        }
				    )
				in
				    ColonnesRenommees

	annotation PBI_ResultType = Table

