table Ventes

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		isHidden
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

	column 'ID magasin'
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: ID magasin

		annotation SummarizationSetBy = User

	column 'ID produit'
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: ID produit

		annotation SummarizationSetBy = User

	column 'Unités'
		dataType: int64
		formatString: #,0
		isHidden
		summarizeBy: none
		sourceColumn: Unités

		annotation SummarizationSetBy = User

	partition Ventes = m
		mode: import
		source =
				// Requête : Ventes (table de faits)
				// Grain : une ligne = un produit vendu dans un magasin à une date donnée
				let
				    Source = Csv.Document(
				        File.Contents(DossierDonnees & "sales.csv"),
				        [Delimiter = ",", Columns = 5, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				    ),
				    EntetesPromues = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    // Sale_ID est unique sur 829 262 lignes : aucune analyse ne l'utilise et une colonne
				    // à valeurs toutes différentes se compresse très mal. La supprimer allège le modèle.
				    ColonnesUtiles = Table.RemoveColumns(EntetesPromues, {"Sale_ID"}),
				    // Culture "en-US" : le fichier source est au format américain
				    TypesAppliques = Table.TransformColumnTypes(
				        ColonnesUtiles,
				        {
				            {"Date", type date},
				            {"Store_ID", Int64.Type},
				            {"Product_ID", Int64.Type},
				            {"Units", Int64.Type}
				        },
				        "en-US"
				    ),
				    ColonnesRenommees = Table.RenameColumns(
				        TypesAppliques,
				        {
				            {"Store_ID", "ID magasin"},
				            {"Product_ID", "ID produit"},
				            {"Units", "Unités"}
				        }
				    )
				in
				    ColonnesRenommees

	annotation PBI_ResultType = Table
