table Ventes
	lineageTag: 2cb9b428-ebe2-47db-bcc6-b4bc49364b3f

	column Date
		dataType: dateTime
		isHidden
		formatString: dd/mm/yyyy
		lineageTag: 05ccac8c-5354-4ff8-981f-13faa759b000
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

	column 'ID magasin'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: af62c9be-46c3-48f5-aa7c-854710d74c3f
		summarizeBy: none
		sourceColumn: ID magasin

		annotation SummarizationSetBy = User

	column 'ID produit'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: bc247ea6-9ab4-427a-970d-9e747cb9321d
		summarizeBy: none
		sourceColumn: ID produit

		annotation SummarizationSetBy = User

	column Unités
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: 5995d3ba-3181-46d5-b5bd-d4c9909ee651
		summarizeBy: none
		sourceColumn: Unités

		annotation SummarizationSetBy = User

	partition Ventes = m
		mode: import
		source =
				// Requête : Ventes (table de faits)
				// Grain : une ligne = un produit vendu dans un magasin à une date donnée
				let
				    // Lecture depuis GitHub (par défaut, fonctionne sur tout poste) ou depuis un dossier local
				    Contenu =
				        if Text.StartsWith(DossierDonnees, "http")
				        then Web.Contents(DossierDonnees & "sales.csv")
				        else File.Contents(DossierDonnees & "sales.csv"),
				    Source = Csv.Document(
				        Contenu,
				        [Delimiter = ",", Columns = 5, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				    ),
				    EntetesPromues = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    // Sale_ID est unique sur 829 262 lignes : aucune analyse ne l'utilise et une colonne
				    // à valeurs toutes différentes se compresse très mal. La supprimer allège le modèle.
				    ColonnesUtiles = Table.RemoveColumns(EntetesPromues, {"Sale_ID"}),
				    // Culture "en-US" : le fichier source est au format américain
				    TypesAppliques = Table.TransformColumnTypes(
				        ColonnesUtiles,
				        {
				            {"Date", type date},
				            {"Store_ID", Int64.Type},
				            {"Product_ID", Int64.Type},
				            {"Units", Int64.Type}
				        },
				        "en-US"
				    ),
				    ColonnesRenommees = Table.RenameColumns(
				        TypesAppliques,
				        {
				            {"Store_ID", "ID magasin"},
				            {"Product_ID", "ID produit"},
				            {"Units", "Unités"}
				        }
				    )
				in
				    ColonnesRenommees

	annotation PBI_ResultType = Table

